default:
  font: Droid Sans
  bold: "{* Bold}"
  mono: Droid Sans Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  thanks: "This is the PDF file of Arch Cookbook."

